* What is this? 
Another Pen Testing Enumeration Tool!

Rewrite of https://gitlab.com/foresitelabs/auto_enum/

* Capabilities

*Your IP Address*
- List your source IP(s) before any scanning takes place

*NetSec*
- Enumeration of IPs and domain names to find ports and services
- Nmap Scanning Engine (NSE) scripts to further enumerate services for common issues
- Output into files that are easily parsed

*Web Applications*
- Performs directory/page discovery using =dirb=
- Lists information about the webserver in use

*Summaries*
- List how many IPs and unique ports/services were discovered

* Prerequisites
This script utilizes the following tools and will not run unless they are installed.
#+BEGIN_SRC 
masscan
dig
curl
nmap
ike-scan
nbtscan
wfuzz
dirb
#+END_SRC

* Setup
First run =aio-enum.sh=

#+BEGIN_SRC shell :results silent
sudo ./aio-enum.sh
#+END_SRC

Next populate the =targets.ip= file

#+BEGIN_SRC shell :results silent
echo "192.168.100.0/24" >> targets.ip
#+END_SRC

Next populate the =exclude.ip= file

#+BEGIN_SRC shell :results silent
echo "192.168.100.5" >> exclude.ip
#+END_SRC

* Usage
*** Running with the default settings:
By default, =aio-enum.sh= will scan *ALL TCP* ports and UDP ports =53,69,123,161,500,1434=.
#+BEGIN_SRC shell :results silent
./aio-enum.sh
#+END_SRC

*** Selecting options:
#+BEGIN_SRC shell :results silent
./aio-enum.sh -h
#+END_SRC
#+BEGIN_SRC 
Usage: ./aio-enum.sh [-1|2|3|4|5|6|h|v]
Options:
1 | --default) Identify Alive IPs and Ports
2 | --quick)   Portscan hosts replying to ICMP
3 | --scans)   Masscan, Nmap and Nmap NSE scripts
4 | --all)     Masscan, Nmap, Nmap NSE scripts and Web dir/page enum
5 | --nmap)    Nmap and NSE scripts - No masscan
6 | --icmp)    Nmap pingSweep only
h | --help)    Print this help
v |            Print version and exit
#+END_SRC

*** Detailed Options
After running the script with/without arguments, you will be presented with a menu. Choose an option to continue.

All options will finish with a summary on the number of alive IP addresses and unique ports that are open!
|              Option | Usage            | Detail                           |
|-----------------+----------------------------+------------------------------------|
|  1 | Alive IPs and Port Enumeration  |  =masscan= and =nmap= are used to perform a pingsweep and portscan. Both tools are parsed to display the no. of Alive IP addresses and no. of open ports. No further probing of open ports is performed!|
|  2 | Default Scans                   |  This will use =masscan=, performing a dns resolution and completing a port scan. It will then run =nmap=, performing a pingsweep and port scan. The results from both tools will be stored in files and then Nmap NSE's will execute against identified open ports. |
|  3 | Default + Dictionary Attacks    |  This performs the same as the above option, but also allows for brute force and dictionary attacks. For example, port 80 being open will utilize =dirb= to enumerate active directories/pages based off of a word list. |
|  4 | Quick Nmap Scan                 |  This jumps straight to Nmap ping sweep + port scan and finishes with NSE scripts. No dictionary attacks. |
|  5 | Nmap & NSE Scripts              |  Nmap ping sweep + port scan and finishes with NSE scripts. No dictionary attacks. |
|  6 | Nmap pingsweep                  |  Nmap pingsweep only |
